### ISSUE TITLE
 I'm getting an error when I try to use templates? It says template parsing error.

### ISSUE THREAD

**Issue by turnerll** [mathisgauthey/obsidian-workflow-template#1]
Do you mind sharing the settings you have for all of your plugins? Also, do you happen to have any scripts for the templator for some reason, I'm getting an error when I try to use templates? It says template parsing error.

**Deleted Personnal Drive Link**

**Comment by mathisgauthey** [comment]
Hi there, you can find the whole templater settings [here](https://github.com/mathisgauthey/obsidian-workflow-template/blob/0aa0b905b99e65efc86230ac3379cb07d275d6c4/.obsidian/plugins/templater-obsidian/data.json), it is in the repository.

I'd suggest searching for `folder templates settings` : 
![image](https://github.com/mathisgauthey/obsidian-workflow-template/assets/46576952/07dee48f-f13d-4f59-83d3-f891c1e2c1d0)

I don't have any, but on your recording, it seems like templater is called when you try to create a file.

**Comment by Kmfernan5** [comment]
Thank you do you mind sharing the settings for all the other plugins

**Comment by Kmfernan5** [comment]
is there any way you could show how you use it in your day to day workflow like for instance how you do the workouts

**Comment by mathisgauthey** [comment]
Well the plugin settings are configured according to my blog post showcasing the workflow.

As for the template, I just right click the workout log folder and select my workout template !

**Comment by Kmfernan5** [comment]
How do you visualize your habits and workouts?

**Comment by mathisgauthey** [comment]
Hey there, to be honest, I'm now using [loop habit tracker](https://loophabits.org/) for habits and [gymstro](https://gymstro.app/) for workouts now.

If you still want to use it in Obsidian and want a representation, i'd suggest these tools :
- https://github.com/Richardsl/heatmap-calendar-obsidian
- https://github.com/phibr0/obsidian-charts
- https://github.com/pyrochlore/obsidian-tracker
