### ISSUE TITLE
TaskBoard missing

### ISSUE THREAD

**Issue by jefftemplon** [mathisgauthey/obsidian-workflow-template#17]
Hi,

This documentation

https://mathisgauthey.github.io/my-complete-obsidian-workflow-to-manage-my-life/

mentions a TaskBoard note.  I cannot find this note in the most recent version of the vault (downloaded yesterday).  Where is it?

Thanks for making your work public.

**Comment by mathisgauthey** [comment]
Hey there ! Thanks for your interest in my stuff, it was removed in version [1.0.0](https://github.com/mathisgauthey/obsidian-workflow-template/releases/tag/1.0.0)

You can still get it from this older version and tweak it to your needs 🕺

**Comment by jefftemplon** [comment]
Thank you, I will keep it in mind for when I might need it.  How do you find "unclarified" tasks in the current version?

**Comment by mathisgauthey** [comment]
If I remember correctly, everything was done in daily and periodic views, allowing for zooming in and zooming out of your projects and tasks easily 🤔

**Comment by jefftemplon** [comment]
It sounds like you are no longer using the system yourself?

**Comment by mathisgauthey** [comment]
I am no longer using obsidian for everything as it was too slow for me on mobile yes !

I use obsidian for taking technical notes, writing blog posts, and reflecting. I am now back to using a proper task management app like Ticktick to manage my actions and calendar ✌️

**Comment by jefftemplon** [comment]
Thanks for your answer.  I don't use Obsidian mobile.  I was using Ideaverse before, that was too slow, but your setup works fine so far!

**Comment by mathisgauthey** [comment]
As stated on my blog post, this is not much of an issue if I don't use it anymore. It is merely a starting point with some accumulated knowledge on which you can build the system that works for you ! I'm just some sort of inspiration let's say.

On a side note, if you happen to make some modifications of fixes on the template, please don't hesitate to create a pull request to share it with others !

Thanks for creating this issue and have a great weekend ✌️

**Comment by jefftemplon** [comment]
Ok thanks.  I may change it to use a different Todo app, do you want such changes as well?  I will in any case make a pointer to your system.
