### ISSUE TITLE
How is lastmod supposed to work?

### ISSUE THREAD

**Issue by jefftemplon** [mathisgauthey/obsidian-workflow-template#19]
Hi,

In the default template a property "lastmod" is included.  When I modify a file, this value does not change.  How is it supposed to work?

Thanks, Jeff

**Comment by mathisgauthey** [comment]
Hey there pal, the `lastmod` is used inside the `obsidian-linter` plugin and is updated each time you save your file.

You can configure it inside the `obsidian-linter` plugin settings, which is related to [this part of the template](https://github.com/mathisgauthey/obsidian-workflow-template/blob/ead0135038481ffbb08849962ca75a98ed0263a2/.obsidian/plugins/obsidian-linter/data.json#L56).

Hope it helps ! Please close the ticket if it is good for you !

**Comment by jefftemplon** [comment]
Thanks, I didn’t even know the concept of “save file” existed - Obsidian seems to do that automatically, but the automatic save does not update that field - a manual save will.

JT
